year: 2026
association: "Association Saint Maurienne des Amis des Animaux (ASMAA)"

# Chemins
paths:
  images_dir: "images"
  output_dir: "calendrier_ASMAA_2026"
  background_image: "images/stella.png"

# Mise en page
layout:
  dpi: 300
  paper:
    width_in: 8.27
    height_in: 11.69
  background_color: "white"
  text_color: "black"
  weekend_bg: "#e8e8e8"
  grid_color: "#cccccc"

  title:
    text_y: 240
    fontsize: 40
    fontweight: "bold"
    color: "#000000"

  cover_photo:
    x: 25
    y: 60
    w: 160
    h: 120

association_style:
  text_y: 215
  fontsize: 20
  fontweight: "bold"
  color: "#000000"
  auto_newline: true
  newline_token: " des "

effects:
  blur_radius: 6
  white_veil_opacity: 0.30
  white_veil_color: "#ffffff"

holidays:
  - [2026, 1, 1, "Jour de l’An"]
  - [2026, 4, 6, "Lundi de Pâques"]
  - [2026, 5, 1, "Fête du Travail"]
  - [2026, 5, 8, "Victoire 1945"]
  - [2026, 5, 14, "Ascension"]
  - [2026, 5, 25, "Lundi de Pentecôte"]
  - [2026, 7, 14, "Fête nationale"]
  - [2026, 8, 15, "Assomption"]
  - [2026, 11, 1, "Toussaint"]
  - [2026, 11, 11, "Armistice"]
  - [2026, 12, 25, "Noël"]
