# Configuration du calendrier ASMAA
year: 2026
association: "Association Saint Maurienne des Amis des Animaux (ASMAA)"

# Chemins
paths:
  images_dir: "images"
  output_dir: "calendrier_ASMAA_2026"
  background_image: "images/stella.png"
# Mise en page
layout:
  dpi: 300
  paper:
    width_in: 8.27    # A4
    height_in: 11.69  # A4
  background_color: "white"
  text_color: "black"
  weekend_bg: "#e8e8e8"
  grid_color: "#cccccc"

effects:
  blur_radius: 6   #  intensité du flou de fond (0 = aucun flou, 10 = très flou)
  white_veil_opacity: 0.30    # voile blanc (0 = désactivé, 1 = blanc total)
  white_veil_color: "#ffffff" # couleur du voile (ex : "#ffffff" pour blanc, "#000000" pour noir)

# Jours fériés français
holidays:
  - [2026, 1, 1, "Jour de l’An"]
  - [2026, 4, 6, "Lundi de Pâques"]
  - [2026, 5, 1, "Fête du Travail"]
  - [2026, 5, 8, "Victoire 1945"]
  - [2026, 5, 14, "Ascension"]
  - [2026, 5, 25, "Lundi de Pentecôte"]
  - [2026, 7, 14, "Fête nationale"]
  - [2026, 8, 15, "Assomption"]
  - [2026, 11, 1, "Toussaint"]
  - [2026, 11, 11, "Armistice"]
  - [2026, 12, 25, "Noël"]
